export const {
  PORT,
  NODE_ENV,
  JWT_EXPIRY_ACCESS,
  JWT_SECRET,
  JWT_EXPIRY_REFRESH,
  AUTHORIZED_ADMIN_ID,
  DB_PASSWORD,
  JWT_REFRESH_SECRET,
  MONGO_URI,
  DB_USERNAME,
  MONGO_DB,
  //
  DEEPSEEK_API_KEY,
  DEEPSEEK_API_URL,
  CLOUDINARY_API_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET_KEY,
  CLOUDINARY_API_URL,
  WEBHOOK_PASSWORD,
  //
  URL_CLIENT,
  URL_FRONTEND,
  //
  SESSION_SECRET_KEY,
   GEMINI_API_KEY,

} = process.env;
